### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by natelowry** [TourCMS/tourcms-dotnet#1]
Would be a lot nicer if this was a NuGet Package.  Any plans on doing that?  Thanks!

**Comment by paulslugocki** [comment]
Hi Nate, sounds like a good idea, thanks for the nudge.

**Comment by paulslugocki** [comment]
We have a NuGet package:

https://www.nuget.org/packages/TourCMS/

Search `TourCMS` in the GUI or `Install-Package TourCMS` via the console.

Feedback on any issues/improvements welcome.

**Comment by natelowry** [comment]
:heart_eyes_cat:  Woot!  Thanks!! :heart_eyes_cat:
